export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const UPDATE_STORYLIST = 'UPDATE_STORYLIST';
export const UPDATE_STORYDETAILS = 'UPDATE_STORYDETAILS';
export const TOGGLE_SIDEMENU = 'TOGGLE_SIDEMENU';
export const UPDATE_SIDEMENUSTATE = 'UPDATE_SIDEMENUSTATE';
export const ON_SIDEMENUITEM_SELECTED = 'ON_SIDEMENUITEM_SELECTED';